### ISSUE TITLE
Demo server not working

### ISSUE THREAD

**Issue by newzen** [afaqurk/hunts-point-pos#5]
Hello,

Would you start demo server?

thanks in advance

**Comment by afaqurk** [comment]
There is an issue with the hunts-point-pos demo. It started consuming a lot of memory unexpectedly. I will have to debug it when I have free time before I enable it.

It might take a while before I restart the demo.

**Comment by Larceniii** [comment]
Any chance you could post screenshots if the demo keeps going down?

**Comment by afaqurk** [comment]
Will do.

**Comment by Larceniii** [comment]
Thanks

**Comment by Larceniii** [comment]
@afaqurk Were you able to get the screenshots?

**Comment by afaqurk** [comment]
Even better. The demo is back up: http://pos.afaqtariq.com/
