### ISSUE TITLE
why my layout is err

### ISSUE THREAD

**Issue by yaodehaung** [afaqurk/hunts-point-pos#7]
![2016-07-08 11 46 50](https://cloud.githubusercontent.com/assets/8554998/16693159/7c9d1b32-4566-11e6-9f3d-d74a2c53229b.png)

**Comment by afaqurk** [comment]
You'll have to provide some error logs before I can help you. Check your browser console and node process output in terminal.

**Comment by yaodehaung** [comment]
thx . My issue is save.
